application: mail
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: main.application
  login: required

libraries:
- name: jinja2
  version: latest

inbound_services:
- mail
