application: xmpp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/.*
  script: main.application
  login: admin

- url: .*
  script: main.application
  login: required

libraries:
- name: jinja2
  version: latest

inbound_services:
- xmpp_message
- xmpp_error
- xmpp_subscribe
- xmpp_presence
