application: deferred
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/
  login: admin
- url: /
  script: main.py
  login: required
