application: cron
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/queue/default
  script: task.py
  login: admin
- url: /send_invitation_task
  script: task.py
  login: admin
- url: /
  script: taskenqueue.py
