application: secureconnections
version: 1
runtime: python
api_version: 1

handlers:
- url: /always
  script: main.py
  secure: always

- url: /never
  script: main.py
  secure: never

- url: /optional
  script: main.py
  secure: optional

- url: /
  script: main.py
