application: async
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /callbackobj
  script: callbackobj.app
- url: /callbackfunc
  script: callbackfunc.app
